# Conda environment for developpers

name: museotoolbox-dev
dependencies:
	# ReadTheDoc dependencies
	- mock
	- pillow
	- sphinx
	- sphinx_rtd_theme
	# other dependencies
        - python=3.7
        - pytest
        - gdal
        - pip 
        - pip:
          - -r file:requirements-dev.txt
