# Install env for building the doc via readthedocs

name: museotoolbox
dependencies:
        - python=3.7
        - GDAL
        - pip:
           - nbsphinx
           - sphinx-rtd-theme
           - sphinx-gallery
           - joblib

